import { Fragment, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { Icon, SectionLabel } from "@/components/common/primitives";
import { useInspector } from "@/components/common/Inspector";
import type { AskResult } from "@/api/types";

/** A passage the answer relies on (from `sources` in the /api/answers payload). */
export type CitedSource = {
  document_id: string;
  chunk_id?: string;
  title: string;
  document_type?: string;
  matter_id?: string;
  matter_code?: string;
  snippet?: string;
};

type MatchedMatter = { matter_id: string; matter_code: string; title: string; client_name?: string; court?: string };

function str(v: unknown): string | undefined {
  return v === null || v === undefined || v === "" ? undefined : String(v);
}

export function citedSources(result: AskResult): CitedSource[] {
  const seen = new Set<string>();
  const out: CitedSource[] = [];
  for (const raw of [...(result.sources ?? []), ...(result.structured_citations ?? [])]) {
    const document_id = str(raw.document_id);
    if (!document_id || seen.has(document_id)) continue;
    seen.add(document_id);
    out.push({
      document_id,
      chunk_id: str(raw.chunk_id),
      title: str(raw.title) ?? document_id,
      document_type: str(raw.document_type),
      matter_id: str(raw.matter_id),
      matter_code: str(raw.matter_code),
      snippet: str(raw.snippet),
    });
  }
  return out;
}

/** Split text on DOC-##### references and render each as a clickable citation chip. */
export function withCitationChips(text: string, onCite: (documentId: string) => void): ReactNode[] {
  return text.split(/(\[?\(?DOC-\d+\)?\]?)/g).map((part, i) => {
    const m = part.match(/DOC-\d+/);
    if (!m) return <Fragment key={i}>{part}</Fragment>;
    return (
      <button
        key={i}
        type="button"
        onClick={() => onCite(m[0])}
        className="mx-0.5 inline-flex items-center rounded-[3px] bg-wine-soft px-1 align-baseline font-mono-id text-[11px] font-semibold text-wine transition-colors hover:bg-wine hover:text-primary-foreground"
        data-testid={`citation-${m[0]}`}
      >
        {m[0]}
      </button>
    );
  });
}

export function AIAssembling({ label = "Searching the firm's records within your access scope…" }: { label?: string }) {
  return (
    <div className="flex items-center gap-3 py-6 text-sm text-muted-foreground" data-testid="ai-assembling" role="status">
      <span className="h-2 w-2 animate-pulse rounded-full bg-wine" />
      {label}
    </div>
  );
}

export function AIAnswer({ result }: { result: AskResult }) {
  const inspector = useInspector();
  const sources = citedSources(result);
  const openDoc = (documentId: string) => {
    const src = sources.find((s) => s.document_id === documentId);
    inspector?.open({ type: "document", id: documentId, chunkId: src?.chunk_id });
  };

  if (result.abstained) {
    return (
      <div className="rounded-lg border border-border bg-card p-6" data-testid="ai-abstained">
        <div className="eyebrow text-muted-foreground">No grounded answer</div>
        <p className="mt-2 text-[15px] leading-relaxed">
          The firm's records you can access don't support an answer to this question
          {result.reason ? ` (${String(result.reason).replace(/_/g, " ")})` : ""}. Try naming the matter, party or forum.
        </p>
      </div>
    );
  }

  const paragraphs = (result.answer ?? "").split(/\n{2,}/).map((p) => p.trim()).filter(Boolean);

  return (
    <div className="space-y-8" data-testid="ai-answer">
      {result.key_finding && (
        <div className="rounded-lg border border-wine/30 bg-wine-soft/40 p-5">
          <div className="meta-label mb-1 text-wine">Key finding</div>
          <p className="font-display text-xl leading-snug text-ink">{withCitationChips(String(result.key_finding), openDoc)}</p>
        </div>
      )}
      <div className="space-y-4 text-[16px] leading-[1.75] text-foreground">
        {paragraphs.map((p, i) => (
          <p key={i} className="whitespace-pre-wrap">
            {withCitationChips(p, openDoc)}
          </p>
        ))}
      </div>
      {result.provider && (
        <p className="text-xs text-muted-foreground">
          {String(result.provider).startsWith("extractive")
            ? "Assembled from retrieved passages (the language model did not produce a grounded answer)."
            : `Generated by ${String(result.provider)} from the passages below.`}
        </p>
      )}
    </div>
  );
}

/** Right-hand context column: the cited sources and the matters they come from. */
export function AnswerContext({ result }: { result: AskResult }) {
  const inspector = useInspector();
  const sources = citedSources(result);
  const matters = (result.matchedMatters as MatchedMatter[] | undefined) ?? [];

  return (
    <div className="space-y-8">
      <div>
        <SectionLabel>Sources ({sources.length})</SectionLabel>
        {sources.length === 0 ? (
          <p className="text-sm text-muted-foreground">No sources.</p>
        ) : (
          <ul className="space-y-3" data-testid="answer-sources">
            {sources.map((s) => (
              <li key={s.document_id}>
                <button
                  type="button"
                  onClick={() => inspector?.open({ type: "document", id: s.document_id, chunkId: s.chunk_id })}
                  className="block w-full text-left"
                >
                  <span className="font-mono-id text-[11px] text-wine">{s.document_id}</span>
                  <span className="block text-sm text-foreground hover:text-wine">{s.title}</span>
                  <span className="block text-xs text-muted-foreground">{[s.document_type, s.matter_code].filter(Boolean).join(" · ")}</span>
                </button>
              </li>
            ))}
          </ul>
        )}
      </div>
      {matters.length > 0 && (
        <div>
          <SectionLabel>Matters</SectionLabel>
          <ul className="space-y-3">
            {matters.map((m) => (
              <li key={m.matter_id}>
                <Link to={`/matters/${m.matter_id}`} className="group block">
                  <span className="font-mono-id text-[11px] text-muted-foreground">{m.matter_code}</span>
                  <span className="block text-sm group-hover:text-wine">{m.client_name ?? m.title}</span>
                  {m.court && <span className="block text-xs text-muted-foreground">{m.court}</span>}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      )}
      <p className="flex items-start gap-1.5 text-xs text-muted-foreground">
        <Icon name="visibility_lock" style={{ fontSize: 14 }} /> Only records within your access scope were searched.
      </p>
    </div>
  );
}
